export const itemsConstants = {
    GET_ITEMS_REQUEST : 'GET_ITEMS_REQUEST',
    GET_ITEMS_SUCCESS : 'GET_ITEMS_SUCCESS',

    ADD_ITEM_TO_CART        : 'ADD_ITEM_TO_CART',
    REMOVE_ITEM_FROM_CART   : 'REMOVE_ITEM_FROM_CART',

    GET_ITEM_DETAILS_REQUEST: 'GET_ITEM_DETAILS_REQUEST',
    GET_ITEM_DETAILS_SUCCESS: 'GET_ITEM_DETAILS_SUCCESS'
}